### ISSUE TITLE
look into billing issue gcp

### ISSUE THREAD

**Issue by nicflores** [precog/quasar-datasource-gcs#89]
This PR has a build issue:

https://github.com/precog/quasar-datasource-gcs/pull/88

It seems like there's an error accessing `/testdata/lines.json` and `/testdata/array.json`:

```
$ gsutil cp gs://precog-test-bucket/testdata/lines.json /tmp/lines.json

Copying gs://precog-test-bucket/testdata/lines.json...
AccessDeniedException: 403 HttpError accessing
...
content <The project to be billed is associated with an absent billing account.>
```

So we need to look into what's happening with billing for the `precog-ci` GCP project.

**Comment by nicflores** [comment]
I might have to reach out to GCP billing support.

**Comment by nicflores** [comment]
<1>

**Comment by alissapajer** [comment]
@beckyconning this blocks auto-bumps to `precog/slamx`. We could simply remove `quasar-datasource-gcs` as a dependency from `precog/slamx` if we want to unblock auto-bumps. If we want to release `precog/quasar-datasource-gcs` we'll have to fix this issue.

**Comment by alissapajer** [comment]
<0>

**Comment by alissapajer** [comment]
closed by https://github.com/precog/quasar-datasource-gcs/pull/88
